# Site settings
title: Wenhow Li Homepage 
email: whenhowlee@qq.com
description: > # this means to ignore newlines until "baseurl:"
  This is my teaching and research blog. Welcome to your visit. I am looking forward for your message.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://4instructor.com" # the base hostname & protocol for your site
#twitter_username: jekyllrb
#github_username:  whenhowlee

# Build settings
markdown: kramdown
encoding: utf-8
